services:
  db:
    image: postgres:16
    container_name: sqlbootcamp_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: udemy_sql
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d udemy_sql"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./sql-ultimate-course/datasets/postgres/initdb:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
